server:
    verbosity: 1
    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 capability
    do-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If for some reason root.hints cannot be fetched, leave this commented out.
    # root-hints: "/opt/unbound/etc/unbound/root.hints"

    # Trust anchor file, used for DNSSEC
    auto-trust-anchor-file: "/opt/unbound/etc/unbound/var/root.key"

    # Buffer size set for the respective environment in use
    so-rcvbuf: 4m
    so-sndbuf: 4m

    # Ensure privacy of local network addresses
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8

    # Access control allowed from host loopback configurations
    access-control: 127.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow

    # Hide identity and version for basic security
    hide-identity: yes
    hide-version: yes

    # Optimizations
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: no
    edns-buffer-size: 1232
    prefetch: yes
    num-threads: 1
